/**
 * Multi-Channel Notification Service for Fodda MCP
 * Dispatches quarterly J-Lens concept workspace sweep reports via Email and Slack.
 * 
 * Fodda House Rules:
 * - Test sends go ONLY to nathan@searchshop.ai and piers.fawkes@psfk.com.
 * - US spelling, no em dashes, direct language.
 */

export interface JLensConditionResult {
    condition: string;
    description: string;
    modelsEvaluated: string[];
    top10ConceptRank: number;
    layerPersistenceSpan: number;
    tokenSplits: {
        Fodda: number;
        PSFK: number;
    };
    safetyCoLightingSignals: {
        injection: boolean;
        fake: boolean;
        override: boolean;
    };
}

export interface JLensSweepReport {
    timestamp: string;
    quarterLabel: string;
    totalConditions: number;
    targetModels: string[];
    conditionResults: JLensConditionResult[];
    summary: {
        passed: boolean;
        alertTriggered: boolean;
        alerts: string[];
    };
}

export interface NotificationResult {
    emailSent: boolean;
    slackSent: boolean;
    errors: string[];
}

/**
 * Format markdown content for Email and Slack reporting.
 */
function formatReportMarkdown(report: JLensSweepReport): string {
    const lines: string[] = [];

    lines.push(`# Quarterly J-Lens Concept Workspace Sweep Report (${report.quarterLabel})`);
    lines.push(`**Date**: ${report.timestamp}`);
    lines.push(`**Models Evaluated**: ${report.targetModels.join(', ')}`);
    lines.push(`**Status**: ${report.summary.passed ? 'PASSED' : 'ALERT'}`);
    lines.push('');

    if (report.summary.alertTriggered && report.summary.alerts.length > 0) {
        lines.push('### Active Alerts');
        report.summary.alerts.forEach((alert) => {
            lines.push(`- WARNING: ${alert}`);
        });
        lines.push('');
    }

    lines.push('### Matrix Results by Condition');
    lines.push('');
    lines.push('| Condition | Top-10 Rank | Layer Persistence | Fodda Token % | Safety Signals |');
    lines.push('| --------- | ----------- | ----------------- | ------------- | -------------- |');

    report.conditionResults.forEach((res) => {
        const safetyFlags = [];
        if (res.safetyCoLightingSignals.injection) safetyFlags.push('injection');
        if (res.safetyCoLightingSignals.fake) safetyFlags.push('fake');
        if (res.safetyCoLightingSignals.override) safetyFlags.push('override');
        const safetyStr = safetyFlags.length > 0 ? safetyFlags.join(', ') : 'None';

        lines.push(
            `| ${res.condition} | #${res.top10ConceptRank} | ${res.layerPersistenceSpan} layers | ${res.tokenSplits.Fodda}% | ${safetyStr} |`
        );
    });

    lines.push('');
    lines.push('---');
    lines.push('Automated report generated by Fodda MCP J-Lens Review Pipeline.');

    return lines.join('\n');
}

/**
 * Send J-Lens sweep notifications via Email (Resend) and Slack.
 * 
 * Fodda House Rules Enforcement:
 * Recipient list is strictly restricted to nathan@searchshop.ai and piers.fawkes@psfk.com.
 */
export async function sendJLensSweepNotifications(
    report: JLensSweepReport
): Promise<NotificationResult> {
    const result: NotificationResult = {
        emailSent: false,
        slackSent: false,
        errors: [],
    };

    const allowedRecipients = ['nathan@searchshop.ai', 'piers.fawkes@psfk.com'];
    const markdownContent = formatReportMarkdown(report);

    // 1. Dispatch Email via Resend
    const resendKey = process.env.RESEND_API_KEY;
    if (!resendKey) {
        const msg = '[notifications] RESEND_API_KEY not configured. Skipping email send.';
        console.warn(msg);
        result.errors.push(msg);
    } else {
        try {
            const { Resend } = await import('resend');
            const resend = new Resend(resendKey);
            const statusLabel = report.summary.passed ? 'PASSED' : 'ALERT';
            const subject = `[J-Lens Sweep] ${report.quarterLabel} Concept Workspace Report: ${statusLabel}`;

            const htmlContent = `
                <div style="font-family: sans-serif; max-width: 680px; margin: 0 auto; padding: 20px; color: #111;">
                    <h2 style="color: #0b57d0;">Quarterly J-Lens Concept Workspace Sweep (${report.quarterLabel})</h2>
                    <p><strong>Timestamp:</strong> ${report.timestamp}</p>
                    <p><strong>Evaluated Models:</strong> ${report.targetModels.join(', ')}</p>
                    <p><strong>Status:</strong> <span style="font-weight: bold; color: ${report.summary.passed ? '#0d6efd' : '#dc3545'};">${statusLabel}</span></p>
                    
                    ${
                        report.summary.alerts.length > 0
                            ? `<div style="background-color: #f8d7da; border: 1px solid #f5c6cb; color: #721c24; padding: 12px; border-radius: 4px; margin-bottom: 20px;">
                                <strong>Alerts Triggered:</strong>
                                <ul>${report.summary.alerts.map((a) => `<li>${a}</li>`).join('')}</ul>
                               </div>`
                            : ''
                    }

                    <h3>Matrix Condition Results</h3>
                    <table border="1" cellpadding="8" cellspacing="0" style="border-collapse: collapse; width: 100%; text-align: left;">
                        <thead>
                            <tr style="background-color: #f1f3f4;">
                                <th>Condition</th>
                                <th>Top-10 Rank</th>
                                <th>Layer Persistence</th>
                                <th>Fodda Token %</th>
                                <th>Safety Signals</th>
                            </tr>
                        </thead>
                        <tbody>
                            ${report.conditionResults
                                .map((c) => {
                                    const sFlags = [];
                                    if (c.safetyCoLightingSignals.injection) sFlags.push('injection');
                                    if (c.safetyCoLightingSignals.fake) sFlags.push('fake');
                                    if (c.safetyCoLightingSignals.override) sFlags.push('override');
                                    return `
                                    <tr>
                                        <td><strong>${c.condition}</strong></td>
                                        <td>#${c.top10ConceptRank}</td>
                                        <td>${c.layerPersistenceSpan} layers</td>
                                        <td>${c.tokenSplits.Fodda}%</td>
                                        <td>${sFlags.length > 0 ? sFlags.join(', ') : 'None'}</td>
                                    </tr>`;
                                })
                                .join('')}
                        </tbody>
                    </table>

                    <p style="margin-top: 24px; font-size: 12px; color: #666;">
                        This email was sent to authorized internal recipients per Fodda House Rules.
                    </p>
                </div>
            `;

            await resend.emails.send({
                from: 'Fodda MCP J-Lens <reports@fodda.ai>',
                to: allowedRecipients,
                subject,
                text: markdownContent,
                html: htmlContent,
            });

            result.emailSent = true;
            console.log(`[notifications] Email successfully dispatched to ${allowedRecipients.join(', ')}`);
        } catch (err: any) {
            const msg = `[notifications] Email dispatch error: ${err?.message || err}`;
            console.error(msg);
            result.errors.push(msg);
        }
    }

    // 2. Dispatch Slack Notification
    const slackWebhookUrl = process.env.SLACK_WEBHOOK_URL;
    const slackBotToken = process.env.SLACK_BOT_TOKEN;

    if (!slackWebhookUrl && !slackBotToken) {
        const msg = '[notifications] Neither SLACK_WEBHOOK_URL nor SLACK_BOT_TOKEN configured. Skipping Slack post.';
        console.warn(msg);
        result.errors.push(msg);
    } else {
        try {
            const statusEmoji = report.summary.passed ? ':white_check_mark:' : ':warning:';
            const slackText = `${statusEmoji} *Quarterly J-Lens Concept Workspace Sweep Report (${report.quarterLabel})*\n` +
                `*Status*: ${report.summary.passed ? 'PASSED' : 'ALERT'}\n` +
                `*Models*: ${report.targetModels.join(', ')}\n` +
                (report.summary.alerts.length > 0 ? `*Alerts*: ${report.summary.alerts.join(' | ')}\n` : '') +
                `\`\`\`\n${report.conditionResults.map(r => `${r.condition.padEnd(20)} Rank:#${r.top10ConceptRank} Layers:${r.layerPersistenceSpan} Fodda:${r.tokenSplits.Fodda}%`).join('\n')}\n\`\`\``;

            if (slackWebhookUrl) {
                const resp = await fetch(slackWebhookUrl, {
                    method: 'POST',
                    headers: { 'Content-Type': 'application/json' },
                    body: JSON.stringify({
                        text: slackText,
                    }),
                });
                if (resp.ok) {
                    result.slackSent = true;
                    console.log('[notifications] Slack message posted via webhook.');
                } else {
                    const errText = await resp.text();
                    result.errors.push(`[notifications] Slack webhook error: ${resp.status} - ${errText}`);
                }
            } else if (slackBotToken) {
                const resp = await fetch('https://slack.com/api/chat.postMessage', {
                    method: 'POST',
                    headers: {
                        'Authorization': `Bearer ${slackBotToken}`,
                        'Content-Type': 'application/json',
                    },
                    body: JSON.stringify({
                        channel: '#fodda-internal',
                        text: slackText,
                        unfurl_links: false,
                    }),
                });
                const body = (await resp.json()) as any;
                if (body.ok) {
                    result.slackSent = true;
                    console.log('[notifications] Slack message posted to #fodda-internal.');
                } else {
                    result.errors.push(`[notifications] Slack API error: ${body.error}`);
                }
            }
        } catch (err: any) {
            const msg = `[notifications] Slack dispatch error: ${err?.message || err}`;
            console.error(msg);
            result.errors.push(msg);
        }
    }

    return result;
}
